Doc for `get_or_set` [ci skip]
leighmcculloch/filecache-ruby pull request #5
Opened 2017-04-05 23:35 UTC by ecoologic

2017-04-13 06:42 UTC, leighmcculloch requested changes
One thing that needs fixing, otherwise 👍 .

2017-04-13 06:42 UTC, leighmcculloch commented on README.md
> +cache.get_or_set("key" { 2 } # 1 (cached value is returned, block is not executed)
The `get_or_set` function call is missing a closing parenthesis.

2017-04-19 03:44 UTC, ecoologic commented
Oops... good catch - corrected.
@leighmcculloch

2017-04-19 03:54 UTC, leighmcculloch approved these changes

2017-04-19 03:55 UTC, merged

2017-04-19 03:55 UTC, leighmcculloch commented
Thanks @ecoologic!